### PR TITLE
Add support for tpsl bracket order placements

### PR DESCRIPTION
**Pull request by desaperados**
Fixes [this issue](https://github.com/nomeida/hyperliquid/issues/3).

Updated `placeOrder()` to be more consistent with the [exchange endpoint](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/api/exchange-endpoint). specification, allowing for multiple orders to be sent in a single request as an array of order objects. Also allows for `vaultAddress`, `grouping` and `builder` properties to be sent in their correct positions as specified by the endpoint where they apply across the entire bracket of orders.

The change is non-breaking and compatible with the current implementation of `placeOrder()` so that passing a single order object will continue to work as expected:

```typescript
// Current behaviour - still supported
placeOrder({
    coin: 'BTC-PERP', 
    is_buy: true,
    sz: 1
    ...
    vaultAddress: '0x...'
})
```
But now multiple orders can also be handled when the request is structured as per the exchange endpoint. `vaultAddress`, `grouping` and `builder` are optional properties, with `grouping` defaulting to 'na' if not provided.

```typescript
// Additional behaviour - handle multiple orders
placeOrder({
    orders: [{coin: 'BTC-PERP', ...}, [coin: 'BTC-PERP', ...]],
    vaultAddress: '0x...',
    grouping: 'normalTpsl',
    builder: {
        address: '0x...',
        fee: 1
    }
})
```

When looking up `assetIndex` on multiple orders the result is cached to avoid repeated http requests.

Housekeeping notes:

Included a commit to remove the `dist/` directory as it is not good practice to have generated directories included in version control. I added the directory to `files` in `package.json` ensuring that it will get included by npm during the build process which also fixes [this issue](https://github.com/nomeida/hyperliquid/issues/8).

Whitespace has been stripped from all changed files.

### CODE REVIEW

**Comment by Sotatek-ElvisPhuong** [comment]
@desaperados , Thanks for your PR, I am also getting this issue of cannot place TP/SL order.
I'm following your implementation but it seems does not work yet.
Also  i have a question:
What is the builder.address and builder.fee? Where can I take it?

**Comment by Sotatek-ElvisPhuong** [comment]
Screenshot 2567-11-27 at 14 04 13

**Comment by desaperados** [comment]
Place order should be working as described - I'm using it for live trading. Builder codes are described in the hyperliquid [documentation](https://hyperliquid.gitbook.io/hyperliquid-docs/trading/builder-codes). They were introduced recently so I added to placeOrder just for completeness.

**Comment by Sotatek-ElvisPhuong** [comment]
ahh @desaperados , I tried on testnet with RPC and chain id of Arbitrum Sepolia: https://app.hyperliquid-testnet.xyz/trade and it did not work.
But when i try your implementation on Mainnet then it worked as expected. Thank you so much!

**Pull request merged**
